" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" Turn on syntax highlighting
syntax on

" Enable filetype detection
filetype on

" Enable filetype-specific indenting
filetype indent on

" Enable filetype-specific plugins
filetype plugin on

" =============== Vundle Initialization ===============
" This loads all the plugins specified in ~/.vim/vundle.vim
" Use Vundle plugin to manage all other plugins
if filereadable(expand("~/.vim/vundle.vim"))
  source ~/.vim/vundle.vim
endif

" Allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Store lots of :cmdline history
set history=1000

" Show incomplete cmds down the bottom
set showcmd

" Show current mode down the bottom
set showmode

" Find the next match as we type the search
set incsearch

" Turn searches case-insensitive
set ignorecase

" Turn searches case-sensitive when upper-case character included, so /foo matches FOO and fOo, but /FOO only matches the former
set smartcase

" Highlight searches by default
set hlsearch

" Clear highlight
nmap \q :nohlsearch<CR>

" Add line numbers
set number

set showbreak=...
set wrap linebreak nolist

" Turn off needless toolbar on gvim/mvim
set guioptions-=T

" Indent settings
set shiftwidth=2
set softtabstop=2
set expandtab
set autoindent

" Fold based on indent
set foldmethod=indent

" Deepest fold is 3 levels
set foldnestmax=3

" Dont fold by default
set nofoldenable

" Make cmdline tab completion similar to bash
set wildmode=list:longest

" Enable ctrl-n and ctrl-p to scroll thru matches
set wildmenu

" Stuff to ignore when tab completing
set wildignore=*.o,*.obj,*~,*.class,*/target/*

" Vertical/horizontal scroll off settings
set scrolloff=3
set sidescrolloff=7
set sidescroll=1

" Allow unsaved buffers to become hiden
set hidden

" Jump to the window if a buffer is already opened in one
set switchbuf=useopen

" Turn Off Swap Files
set noswapfile
set nobackup
set nowb

" Keep undo history across sessions by storing it in file
silent !mkdir ~/.vim/backups > /dev/null 2>&1
set undodir=~/.vim/backups
set undofile

" Switching between current and alternate file (last one edited in the current window) (C-6 does not work on Mac)
nmap <C-e> :e#<CR>

" Convenient way to open next buffer
nmap <C-n> :bnext<CR>

" Convenient way to open previous buffer
nmap <C-p> :bprev<CR>

" Toggles NERDTree
nmap <silent> <Leader>p :NERDTreeToggle<CR>

" List chars
set list

" Reset the listchars
set listchars=""

" A tab should display as "  ", trailing whitespace as "."
set listchars=tab:\ \

" Show trailing spaces as dots
set listchars+=trail:.

" The character to show in the last column when wrap is
" off and the line continues beyond the right of the screen
set listchars+=extends:>

" The character to show in the last column when wrap is
" off and the line continues beyond the left of the screen
set listchars+=precedes:<

" Remove trailing spaces when saving
autocmd BufWritePre * :%s/\s\+$//e

set background=dark
colorscheme jellybeans
